{
   "_id": "_design/bhl",
   "_rev": "7-e17800ac2c80827d0d8dee62ed2c5a24",
   "language": "javascript",
   "views": {
       "epithet": {
           "map": "// Output pairs of names with same epithet on same page\nfunction(doc) {\n  if (doc.names) {\n\n    // Build list of species names for each page\n    var pages = {};\n    for (var i in doc.names) {   \n      \n      for (var j in doc.names[i].pages) {\n         var page_number = doc.names[i].pages[j];\n \n         if (!pages[page_number]) {\n            pages[page_number] = {};\n         }\n         \n         var handle = true;\n         \n         // Ignore names that start with abbreviated genus\n         if (doc.names[i].namestring.match(/^[A-Z]\\./)) {\n         \thandle = false;\n         }\n\n         // Ignore names that start with parentheses\n         if (doc.names[i].namestring.match(/^\\(/)) {\n         \thandle = false;\n         }\n         \n         // Ignore bogus names from GNDR\n         if (doc.names[i].namestring.match(/^Arten/)) {\n         \thandle = false;\n         } \n         \n         if (handle) {         \n\t\t\t var delimiter = doc.names[i].namestring.lastIndexOf(' ');\n\t\t\t if (delimiter != -1) {\n\t\t\t   genus = doc.names[i].namestring.substring(0, delimiter);\n\t\t\t   species = doc.names[i].namestring.substring(delimiter+1);\n\t\n\t\t\t   // handle epithets in names that have genus abbreviated as one letter\n\t\t\t   species = species.replace(/\\. /, '');\n\t\n\t\t\t   if (!pages[page_number][species]) {\n\t\t\t\t pages[page_number][species] = [];\n\t\t\t   }\n\t\t\t   // ignore abbreviated generic names\n\t\t\t   if (genus.length > 1) {\n\t\t\t\tpages[page_number][species].push(genus);\n\t\t\t   }\n\t\t\t }\n\t\t }\n        \n      }\n    }\n\n    // Do pairwise comparison within page\n    for (page_number in pages) {\n       for (species in pages[page_number]) {\n          if (pages[page_number][species].length > 1) {\n            for (j in pages[page_number][species]) {\n              for (k in pages[page_number][species]) {\n                 if (j != k) {\n                  var s1 = pages[page_number][species][j] + ' ' + species;\n                  var s2 = pages[page_number][species][k] + ' ' + species;\n                  emit (s1,[s2, page_number, species]);\n                  }\n                }\n              }\n            }\n          }\n        }\n    \n  }      \n}  "
       }
   }
}